import { ethers } from "ethers";
import solc from "solc";
import fs from "fs";
import path from "path";
import dotenv from "dotenv";

dotenv.config();

/**
 * Deploys PlayFiTreasury — the shared, game-logic-free treasury for Mines,
 * Spin to Win, and Two Doors. Writes the deployed address + ABI to
 * src/contracts/PlayFiTreasury.js and server/config/playFiTreasury.js.
 *
 * Required in .env:
 *   TREASURY_PRIVATE_KEY   - deployer key (becomes the contract owner/admin); needs testnet HBAR for gas
 *
 * Optional (defaults to the PlayFi platform wallet you provided):
 *   FEE_RECIPIENT_ADDRESS  - wallet the 5% platform fees are withdrawn to
 *   FUND_POOL_HBAR         - seed this much initial payout liquidity (0/unset = skip)
 *
 * Run: node scripts/deployTreasury.js
 */

// PlayFi platform fee wallet (Hedera account 0.0.9693203).
const DEFAULT_FEE_RECIPIENT = "0x30ce1d662AA1d9057F28f278Db88cE21fc17AaeB";

const TREASURY_DIR = path.resolve("contracts", "treasury");

function findImport(importPath) {
    if (importPath.startsWith("@openzeppelin/")) {
        const p = path.resolve("node_modules", importPath);
        if (fs.existsSync(p)) return { contents: fs.readFileSync(p, "utf8") };
    }
    return { error: `File not found: ${importPath}` };
}

function compile() {
    const sources = {
        "PlayFiTreasury.sol": { content: fs.readFileSync(path.join(TREASURY_DIR, "PlayFiTreasury.sol"), "utf8") },
    };
    const input = {
        language: "Solidity",
        sources,
        settings: {
            optimizer: { enabled: true, runs: 200 },
            outputSelection: { "*": { "*": ["abi", "evm.bytecode"] } },
        },
    };
    console.log("📦 Compiling PlayFiTreasury.sol (with OpenZeppelin)...");
    const output = JSON.parse(solc.compile(JSON.stringify(input), { import: findImport }));
    if (output.errors) {
        let fatal = false;
        for (const err of output.errors) {
            console.error(err.formattedMessage);
            if (err.severity === "error") fatal = true;
        }
        if (fatal) throw new Error("Compilation failed");
    }
    const c = output.contracts["PlayFiTreasury.sol"]["PlayFiTreasury"];
    return { abi: c.abi, bytecode: c.evm.bytecode.object };
}

async function main() {
    console.log("🚀 Deploying PlayFiTreasury to Hedera Testnet...\n");

    const privateKey = process.env.TREASURY_PRIVATE_KEY || process.env.TESTNET_PRIVATE_KEY;
    if (!privateKey) throw new Error("TREASURY_PRIVATE_KEY is missing in .env");

    const provider = new ethers.JsonRpcProvider("https://testnet.hashio.io/api");
    const wallet = new ethers.Wallet(privateKey, provider);

    const ownerAddress = wallet.address;
    const feeRecipient = ethers.getAddress(process.env.FEE_RECIPIENT_ADDRESS || DEFAULT_FEE_RECIPIENT);

    console.log(`👛 Deployer / owner:  ${ownerAddress}`);
    console.log(`💸 Fee recipient:     ${feeRecipient}${feeRecipient === ethers.getAddress(DEFAULT_FEE_RECIPIENT) ? " (PlayFi platform wallet 0.0.9693203)" : ""}\n`);

    const { abi, bytecode } = compile();

    console.log("⏳ Deploying...");
    const factory = new ethers.ContractFactory(abi, bytecode, wallet);
    const contract = await factory.deploy(ownerAddress, feeRecipient, { gasLimit: 5000000 });
    await contract.waitForDeployment();
    const address = await contract.getAddress();

    console.log("\n✅ SUCCESS!");
    console.log(`🏦 PlayFiTreasury Address: ${address}`);
    console.log(`🌐 Hashscan: https://hashscan.io/testnet/contract/${address}`);

    // Write configs (frontend + backend) so both sides can reference the treasury.
    const abiString = JSON.stringify(abi, null, 2);
    const header = "// Shared PlayFi treasury (Mines, Spin to Win, Two Doors). Generated by scripts/deployTreasury.js.\n";

    const frontendOut = path.resolve("src", "contracts", "PlayFiTreasury.js");
    fs.writeFileSync(frontendOut, `${header}export const PLAYFI_TREASURY_ADDRESS = "${address}";\nexport const PLAYFI_TREASURY_ABI = ${abiString};\n`);
    console.log(`\n💾 Saved ${frontendOut}`);

    const serverOut = path.resolve("server", "config", "playFiTreasury.js");
    fs.writeFileSync(serverOut, `${header}export const PLAYFI_TREASURY_ADDRESS = "${address}";\nexport const PLAYFI_TREASURY_ABI = ${abiString};\n`);
    console.log(`💾 Saved ${serverOut}`);

    // Optionally seed payout liquidity.
    const fund = process.env.FUND_POOL_HBAR;
    if (fund && Number(fund) > 0) {
        console.log(`\n🏦 Seeding payout pool with ${fund} HBAR...`);
        const tx = await contract.fundPool({ value: ethers.parseEther(fund), gasLimit: 500000 });
        await tx.wait();
        console.log("✅ Payout pool funded!");
    } else {
        console.log("\nℹ️  Skipped pool funding (set FUND_POOL_HBAR=<amount> to seed liquidity).");
    }

    console.log("\nNext steps:");
    console.log(`  1. Authorize each game contract:  treasury.setGameAuthorization(<gameAddress>, true)`);
    console.log(`  2. Point the games at this treasury (receiveBet on bet, payout on win).`);
    console.log(`\n🎉 Treasury deployment complete: ${address}`);
}

main().catch((error) => {
    console.error("\n❌ Deployment failed:", error);
    process.exit(1);
});
