import { ethers } from "ethers";
import solc from "solc";
import fs from "fs";
import path from "path";
import dotenv from "dotenv";

dotenv.config();

/**
 * One-shot deployer for the single-treasury PlayFi architecture:
 *   1. PlayFiTreasury  — holds all funds, takes the 5% platform fee.
 *   2. PlayFiGameHub    — the single game contract for Mines, Spin, Two Doors.
 *   3. Authorizes the hub in the treasury and wires the hub -> treasury link.
 *   4. Writes address + ABI configs for the frontend and backend.
 *
 * Required in .env:
 *   TREASURY_PRIVATE_KEY   - deployer key (becomes owner of both contracts); needs testnet HBAR
 *
 * Optional:
 *   FEE_RECIPIENT_ADDRESS  - wallet the 5% fees go to (default: PlayFi platform 0.0.9693203)
 *   BACKEND_SIGNER_ADDRESS - hot wallet the game server uses to settle (default: deployer)
 *   FUND_POOL_HBAR         - seed initial payout liquidity (0/unset = skip)
 *
 * Run: node scripts/deployPlayFi.js
 */

const DEFAULT_FEE_RECIPIENT = "0x30ce1d662AA1d9057F28f278Db88cE21fc17AaeB"; // Hedera 0.0.9693203

function findImport(importPath) {
    const candidates = [];
    if (importPath.startsWith("@openzeppelin/")) {
        candidates.push(path.resolve("node_modules", importPath));
    } else {
        const base = importPath.replace(/^(\.\.\/)+/, "");
        candidates.push(path.resolve("contracts", base));
        candidates.push(path.resolve("contracts", "games", base));
        candidates.push(path.resolve("contracts", "treasury", path.basename(base)));
    }
    for (const c of candidates) {
        if (fs.existsSync(c)) return { contents: fs.readFileSync(c, "utf8") };
    }
    return { error: `File not found: ${importPath}` };
}

function compileAll() {
    const sources = {
        "PlayFiTreasury.sol": { content: fs.readFileSync(path.resolve("contracts", "treasury", "PlayFiTreasury.sol"), "utf8") },
        "PlayFiGameHub.sol": { content: fs.readFileSync(path.resolve("contracts", "games", "PlayFiGameHub.sol"), "utf8") },
    };
    const input = {
        language: "Solidity",
        sources,
        settings: {
            optimizer: { enabled: true, runs: 200 },
            outputSelection: { "*": { "*": ["abi", "evm.bytecode"] } },
        },
    };
    console.log("📦 Compiling PlayFiTreasury + PlayFiGameHub (with OpenZeppelin)...");
    const output = JSON.parse(solc.compile(JSON.stringify(input), { import: findImport }));
    if (output.errors) {
        let fatal = false;
        for (const err of output.errors) {
            console.error(err.formattedMessage);
            if (err.severity === "error") fatal = true;
        }
        if (fatal) throw new Error("Compilation failed");
    }
    return {
        treasury: output.contracts["PlayFiTreasury.sol"]["PlayFiTreasury"],
        hub: output.contracts["PlayFiGameHub.sol"]["PlayFiGameHub"],
    };
}

function writeConfig(frontendPath, serverPath, addrConst, abiConst, address, abi, label) {
    const abiString = JSON.stringify(abi, null, 2);
    const header = `// ${label}. Generated by scripts/deployPlayFi.js.\n`;
    const body = `export const ${addrConst} = "${address}";\nexport const ${abiConst} = ${abiString};\n`;
    fs.writeFileSync(frontendPath, header + body);
    fs.writeFileSync(serverPath, header + body);
    console.log(`💾 Saved ${frontendPath}`);
    console.log(`💾 Saved ${serverPath}`);
}

async function main() {
    console.log("🚀 Deploying the PlayFi single-treasury architecture...\n");

    const privateKey = process.env.TREASURY_PRIVATE_KEY || process.env.TESTNET_PRIVATE_KEY;
    if (!privateKey) throw new Error("TREASURY_PRIVATE_KEY is missing in .env");

    const provider = new ethers.JsonRpcProvider("https://testnet.hashio.io/api");
    const wallet = new ethers.Wallet(privateKey, provider);

    const ownerAddress = wallet.address;
    const feeRecipient = ethers.getAddress(process.env.FEE_RECIPIENT_ADDRESS || DEFAULT_FEE_RECIPIENT);
    const backendSigner = ethers.getAddress(process.env.BACKEND_SIGNER_ADDRESS || ownerAddress);

    console.log(`👛 Deployer / owner:  ${ownerAddress}`);
    console.log(`💸 Fee recipient:     ${feeRecipient}`);
    console.log(`🤖 Backend signer:    ${backendSigner}\n`);

    const { treasury: tArtifact, hub: hArtifact } = compileAll();

    // 1. Treasury
    console.log("⏳ Deploying PlayFiTreasury...");
    const treasury = await new ethers.ContractFactory(tArtifact.abi, tArtifact.evm.bytecode.object, wallet)
        .deploy(ownerAddress, feeRecipient, { gasLimit: 5000000 });
    await treasury.waitForDeployment();
    const treasuryAddress = await treasury.getAddress();
    console.log(`🏦 PlayFiTreasury: ${treasuryAddress}`);

    await new Promise((r) => setTimeout(r, 3000));

    // 2. Hub
    console.log("\n⏳ Deploying PlayFiGameHub...");
    const hub = await new ethers.ContractFactory(hArtifact.abi, hArtifact.evm.bytecode.object, wallet)
        .deploy(ownerAddress, treasuryAddress, backendSigner, { gasLimit: 5000000 });
    await hub.waitForDeployment();
    const hubAddress = await hub.getAddress();
    console.log(`🎮 PlayFiGameHub: ${hubAddress}`);

    await new Promise((r) => setTimeout(r, 3000));

    // 3. Authorize the hub in the treasury
    console.log("\n🔐 Authorizing the hub in the treasury...");
    await (await treasury.setGameAuthorization(hubAddress, true, { gasLimit: 200000 })).wait();
    console.log("✅ Hub authorized.");

    // 4. Configs
    console.log("\n✍️  Writing configs...");
    writeConfig(
        path.resolve("src", "contracts", "PlayFiTreasury.js"),
        path.resolve("server", "config", "playFiTreasury.js"),
        "PLAYFI_TREASURY_ADDRESS", "PLAYFI_TREASURY_ABI",
        treasuryAddress, tArtifact.abi,
        "Shared PlayFi treasury (holds funds, 5% fee, pays winners on hub instruction)"
    );
    writeConfig(
        path.resolve("src", "contracts", "PlayFiGameHub.js"),
        path.resolve("server", "config", "playFiGameHub.js"),
        "PLAYFI_HUB_ADDRESS", "PLAYFI_HUB_ABI",
        hubAddress, hArtifact.abi,
        "Single PlayFi game hub (Mines=0, Spin=1, TwoDoors=2)"
    );

    // 5. Optional pool seeding
    const fund = process.env.FUND_POOL_HBAR;
    if (fund && Number(fund) > 0) {
        console.log(`\n🏦 Seeding payout pool with ${fund} HBAR...`);
        await (await treasury.fundPool({ value: ethers.parseEther(fund), gasLimit: 500000 })).wait();
        console.log("✅ Pool funded.");
    } else {
        console.log("\nℹ️  Skipped pool funding (set FUND_POOL_HBAR=<amount> to seed liquidity).");
    }

    console.log("\n🎉 Done.");
    console.log(`   Treasury: ${treasuryAddress}`);
    console.log(`   Game Hub: ${hubAddress}`);
    console.log(`   Set TREASURY_PRIVATE_KEY on the backend to the backend signer above.`);
}

main().catch((error) => {
    console.error("\n❌ Deployment failed:", error);
    process.exit(1);
});
